const themes = document.getElementsByClassName("t-s-t");
const result = document.getElementsByClassName("res-btn")[0];
const reset = document.getElementsByClassName("re-del-btn")[1];
const del = document.getElementsByClassName("re-del-btn")[0];
const theme = document.getElementById("t-s-b");
const root = document.documentElement.style;
themes[0].addEventListener("click", () => {
  root.setProperty("--num-btn-text-clr", " hsl(221, 14%, 31%)");
  root.setProperty("--not-num-btn-text-clr", "hsl(0, 0%, 100%)");
  root.setProperty("--num-btn-bg-clr", "hsl(30, 25%, 89%)");
  root.setProperty("--del-re-btn-bg-clr", "hsl(225, 21%, 49%)");
  root.setProperty("--res-btn-bg-clr", "hsl(6, 63%, 50%)");
  root.setProperty("--all-btn-full-bg-clr", "hsl(223, 31%, 20%)");
  root.setProperty("--inp-exp-field-bg-clr", "hsl(224, 36%, 15%)");
  root.setProperty("--theme-selector-bg-clr", "hsl(6, 63%, 50%)");
  root.setProperty("--theme-selector-con-bg-clr", " hsl(223, 31%, 20%)");
  root.setProperty("--main-page-bg-clr", "hsl(222, 26%, 31%)");
  root.setProperty("--num-btn-box-shdw-clr", "hsl(28, 16%, 65%)");
  root.setProperty("--del-re-btn-box-shdw-clr", "hsl(224, 28%, 35%)");
  root.setProperty("--res-btn-box-shdw-clr", "hsl(6, 70%, 34%)");
  theme.style.left = "0";
  theme.style.transform = "none";
});
// const root = document.documentElement.style;
themes[1].addEventListener("click", () => {
  root.setProperty("--num-btn-text-clr", "hsl(60, 10%, 19%)");
  root.setProperty("--not-num-btn-text-clr", "hsl(60, 10%, 19%)");
  root.setProperty("--num-btn-bg-clr", " hsl(45, 7%, 89%)");
  root.setProperty("--del-re-btn-bg-clr", " hsl(185, 42%, 37%)");
  root.setProperty("--res-btn-bg-clr", "hsl(25, 98%, 40%)");
  root.setProperty("--all-btn-full-bg-clr", "hsl(0, 5%, 81%)");
  root.setProperty("--inp-exp-field-bg-clr", "hsl(0, 0%, 93%)");
  root.setProperty("--theme-selector-bg-clr", " hsl(25, 98%, 40%)");
  root.setProperty("--theme-selector-con-bg-clr", " hsl(0, 5%, 81%)");
  root.setProperty("--main-page-bg-clr", " hsl(0, 0%, 90%)");
  root.setProperty("--num-btn-box-shdw-clr", "hsl(35, 11%, 61%)");
  root.setProperty("--del-re-btn-box-shdw-clr", "hsl(185, 58%, 25%)");
  root.setProperty("--res-btn-box-shdw-clr", "hsl(25, 99%, 27%)");
  result.style.color = "hsl(0, 0%, 100%)";
  del.style.color = "hsl(0, 0%, 100%)";
  reset.style.color = "hsl(0, 0%, 100%)";
  theme.style.left = "50%";
  theme.style.transform = "translateX(-50%)";
});
// const root = document.documentElement.style;
themes[2].addEventListener("click", () => {
  root.setProperty("--num-btn-text-clr", "hsl(52, 100%, 62%)");
  root.setProperty("--not-num-btn-text-clr", "hsl(52, 100%, 62%)");
  root.setProperty("--num-btn-bg-clr", "hsl(268, 47%, 21%)");
  root.setProperty("--del-re-btn-bg-clr", "hsl(281, 89%, 26%)");
  root.setProperty("--res-btn-bg-clr", "hsl(176, 100%, 44%)");
  root.setProperty("--all-btn-full-bg-clr", "hsl(268, 71%, 12%)");
  root.setProperty("--inp-exp-field-bg-clr", "hsl(268, 71%, 12%)");
  root.setProperty("--theme-selector-bg-clr", "hsl(176, 100%, 44%)");
  root.setProperty("--theme-selector-con-bg-clr", "hsl(268, 71%, 12%)");
  root.setProperty("--main-page-bg-clr", "hsl(268, 75%, 9%)");
  root.setProperty("--num-btn-box-shdw-clr", "hsl(290, 70%, 36%)");
  root.setProperty("--del-re-btn-box-shdw-clr", "hsl(285, 91%, 52%)");
  root.setProperty("--res-btn-box-shdw-clr", "hsl(177, 92%, 70%)");
  result.style.color = "hsl(198, 20%, 13%)";
  del.style.color = "hsl(0, 0%, 100%)";
  reset.style.color = "hsl(0, 0%, 100%)";
  theme.style.left = "100%";
  theme.style.transform = "translateX(-100%)";
});
